# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Torres\Trabajos\DSE\PracticaFinal\PFinalWav\PFinalWav.cydsn\PFinalWav.cyprj
# Date: Wed, 28 May 2014 15:14:43 GMT
#set_units -time ns
create_clock -name {Clock(routed)} -period 90916.666666666657 -waveform {0 45458.3333333333} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {Clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2183 4365} -nominal_period 90916.666666666657 [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]


# Component constraints for C:\Users\Torres\Trabajos\DSE\PracticaFinal\PFinalWav\PFinalWav.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Torres\Trabajos\DSE\PracticaFinal\PFinalWav\PFinalWav.cydsn\PFinalWav.cyprj
# Date: Wed, 28 May 2014 15:14:28 GMT
