/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <WaveDAC8.h>
#include <Pin_Senal.h>
#include <Pin_Senal_aliases.h>
#include <Pin_400.h>
#include <Pin_400_aliases.h>
#include <Pin_500.h>
#include <Pin_500_aliases.h>
#include <Pin_600.h>
#include <Pin_600_aliases.h>
#include <Pin_700.h>
#include <Pin_700_aliases.h>
#include <WaveDAC8_DacClk.h>
#include <WaveDAC8_Wave1_DMA_dma.h>
#include <WaveDAC8_Wave2_DMA_dma.h>
#include <WaveDAC8_VDAC8.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

